import Head from 'next/head'
import Header from '@/components/Header'
import { QuestionMarkCircleIcon } from '@heroicons/react/24/solid'
import Image from 'next/image'
import { banner1, banner2 } from '@/assets'
import Products from '@/components/Products'
import { items } from '@/data/dummyItems'
import ProgressBar from '@/components/ProgressBar'


export default function Home() {

  return (
    <>
      <Head>
        <title>BantuDonasi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='md:w-[30vw] w-full ml-auto mr-auto'>
        <Header />
        <div className='bg-gray-50 h-full w-full' >
          <div className='bg-white w-full' style={{ height: '100vh' }}>
            {/* Items Amal */}
            <h1 className='my-2 font-bold'>Pilihan Bantu Donasi</h1>
            <div>
              <div className='flex flex-row whitespace-nowrap overflow-x-auto scrollbar-hide gap-5 scroll-smooth'>
                {
                  items?.map((v, i) => (
                    <div key={i}>
                      <Products
                        href={v.href}
                        image={v.image}
                        title={v.title}
                        key={i}
                      />
                      <div className='p-2'>
                        <ProgressBar total_fund={v?.total_fund} tmp_fund={v?.tmp_fund} />
                        <div className='flex mt-2 justify-between items-center'>
                          <p className='text-xs font-bold'>Rp {v?.tmp_fund}</p>
                          <p className='text-xs'>{v?.duration} Hari Lagi</p>
                        </div>
                      </div>
                    </div>
                  ))
                }
              </div>
            </div>

            {/* Banner */}
            <div className='my-2'>
              <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1684489563/qurbanearlybird16mei_lkmqtw.jpg' className='w-full h-auto' />
            </div>
            <hr />

            {/* Items Amal */}
            <h1 className='my-2 font-bold'>Spesial Idul Adha</h1>
            <div>
              <div className='flex flex-row whitespace-nowrap overflow-x-auto scrollbar-hide gap-5 scroll-smooth'>
                {
                  items?.map((v, i) => (
                    <div key={i}>
                      <Products
                        href={v.href}
                        image={v.image}
                        title={v.title}
                        key={i}
                      />
                      <div className='p-2'>
                        <ProgressBar total_fund={v?.total_fund} tmp_fund={v?.tmp_fund} />
                        <div className='flex mt-2 justify-between items-center'>
                          <p className='text-xs font-bold'>Rp {v?.tmp_fund}</p>
                          <p className='text-xs'>{v?.duration} Hari Lagi</p>
                        </div>
                      </div>
                    </div>
                  ))
                }
              </div>
            </div>
            <hr />

            {/* Banner */}
            <div className='my-3'>
              <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1684489687/psqpenghafalquran16mei_kz7wyz.jpg' className='w-full h-auto' />
            </div>
            <hr />
            {/* Doa Orang Baik */}
            {/* <div className='my-2'>
              <p className='text-gray-500 font-bold'>Doa-doa Orang Baik #OrangBaik</p>
            </div> */}

            {/* Download App Store */}
            <div className='flex flex-col justify-center items-center'>
              <h5 className='my-5'>Download Aplikasi Bantu Donasi!</h5>
              <div>
                <p className='text-center'>Lebih cepat, bisa donasi mulai Rp1.000 dan tidak memakan banyak memori ponsel</p>
              </div>
              <div className='my-4 md:flex-row flex-col justify-between items-center gap-3'>
                <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1684490084/btn-google-play_ikglu2.png' className='md:w-full h-10 w-full md:h-16' />
                <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1684490084/btn-app-store_i8mik6.png' className='md:w-full h-10 w-full md:h-16' />
              </div>
            </div>

            <div className='flex items-center justify-center'>
              <a href='#' className='text-gray-400 text-center hover:text-gray-500 transition duration-300'>Tentang BantuDonasi</a>
              <p className='mx-2 md:block'>|</p>
              <a href='#' className='text-gray-400 text-center hover:text-gray-500 transition duration-300'>Syarat & Ketentuan</a>
              <p className='mx-2 md:block'>|</p>
              <a href='#' className='text-gray-400 text-center hover:text-gray-500 transition duration-300'>Pusat Bantuan</a>
            </div>

            {/* Sosial Media */}
            <div className='my-5 flex md:px-10 items-center md:justify-between justify-evenly gap-1'>
              <a href='#' className='bg-gray-300 md:w-8 md:h-8 rounded-2xl flex flex-col items-center justify-center md:p-2'>
                <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1684490635/icon-socmed-fb_b0cjri.svg' />
              </a>
              <a href='#' className='bg-gray-300 md:w-8 md:h-8 rounded-2xl flex flex-col items-center justify-center md:p-2'>
                <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1684490879/icon-socmed-twitter_rrsbwa.svg' />
              </a>
              <a href='#' className='bg-gray-300 md:w-8 md:h-8 rounded-2xl flex flex-col items-center justify-center md:p-2'>
                <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1684490881/icon-socmed-instagram_nzawve.svg' />
              </a>
              <a href='#' className='bg-gray-300 md:w-8 md:h-8 rounded-2xl flex flex-col items-center justify-center md:p-2'>
                <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1684490883/icon-socmed-youtube_xciu0p.svg' />
              </a>
              <a href='#' className='bg-gray-300 md:w-8 md:h-8 rounded-2xl flex flex-col items-center justify-center md:p-2'>
                <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1684490886/icon-socmed-tiktok_lilgp9.svg' />
              </a>
              <a href='#' className='bg-gray-300 md:w-8 md:h-8 rounded-2xl flex flex-col items-center justify-center md:p-2'>
                <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1684490887/icon-linkedin_uoqogs.svg' />
              </a>
              <a href='#' className='bg-gray-300 md:w-8 md:h-8 rounded-2xl flex flex-col items-center justify-center md:p-2'>
                <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1684490900/icon-techinasia_arzpzf.svg' />
              </a>
            </div>

            {/* Copyright */}
            <div className='my-5'>
              <p className='text-gray-500 text-center'>Copyright © 2023 BantuDonasi. All Right Reserved</p>
            </div>
            
            <div className='bg-white h-10'>

            </div>
          </div>
        </div>
      </div>
    </>
  )
}
